# Users SCHEMA

# --- !Ups

CREATE TABLE BODY_MEASUREMENT (
  ID         INT          NOT NULL AUTO_INCREMENT,
  PATIENT_ID BIGINT       NOT NULL,
  TYPE       VARCHAR(255) NOT NULL,
  VALUE      DOUBLE       NOT NULL,
  TIMESTAMP  TIMESTAMP    NOT NULL,
  PRIMARY KEY (id)
);

# --- !Downs

DROP TABLE BODY_MEASUREMENT;